# Generated by Django 5.2.1 on 2025-06-23 17:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id_curso', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('ciclo', models.CharField(max_length=20)),
                ('modalidad', models.CharField(max_length=50)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('creditos', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'curso',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id_horario', models.AutoField(primary_key=True, serialize=False)),
                ('dia_semana', models.CharField(max_length=20)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('aula', models.CharField(blank=True, max_length=50, null=True)),
                ('id_curso', models.ForeignKey(db_column='id_curso', on_delete=django.db.models.deletion.CASCADE, to='my_ucsp.curso')),
            ],
            options={
                'db_table': 'horario',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id_matricula', models.AutoField(primary_key=True, serialize=False)),
                ('ciclo', models.CharField(max_length=20)),
                ('fecha_matricula', models.DateField()),
                ('id_curso', models.ForeignKey(db_column='id_curso', on_delete=django.db.models.deletion.CASCADE, to='my_ucsp.curso')),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'matricula',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id_nota', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_nota', models.CharField(max_length=100)),
                ('nota_obtenida', models.DecimalField(decimal_places=2, max_digits=5)),
                ('permanente_promedio', models.CharField(max_length=20)),
                ('peso_porcentaje', models.DecimalField(decimal_places=2, max_digits=5)),
                ('id_matricula', models.ForeignKey(db_column='id_matricula', on_delete=django.db.models.deletion.CASCADE, to='my_ucsp.matricula')),
            ],
            options={
                'db_table': 'nota',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id_tarea', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_tarea', models.CharField(max_length=100)),
                ('fecha_entrega', models.DateField()),
                ('estado', models.CharField(max_length=20)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('id_curso', models.ForeignKey(db_column='id_curso', on_delete=django.db.models.deletion.CASCADE, to='my_ucsp.curso')),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tarea',
                'managed': True,
            },
        ),
    ]
