# Generated by Django 5.2.1 on 2025-06-13 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_ucsp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='curso',
            options={},
        ),
        migrations.AlterModelOptions(
            name='horario',
            options={},
        ),
        migrations.AlterModelOptions(
            name='matricula',
            options={},
        ),
        migrations.AlterModelOptions(
            name='nota',
            options={},
        ),
        migrations.AlterModelOptions(
            name='tarea',
            options={},
        ),
        migrations.AlterModelOptions(
            name='usuario',
            options={},
        ),
    ]
