# Generated by Django 5.2.1 on 2025-06-24 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_ucsp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nota',
            name='permanente_promedio',
        ),
        migrations.AddField(
            model_name='tarea',
            name='categoria',
            field=models.CharField(choices=[('P1', 'Permanente 1'), ('P2', 'Permanente 2'), ('PAR', 'Parcial'), ('FIN', 'Final')], default='P1', help_text='Categoría principal a la que pertenece esta tarea', max_length=3),
        ),
        migrations.AddField(
            model_name='tarea',
            name='peso_porcentaje',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Peso (%) que aporta esta tarea a la nota principal', max_digits=5),
        ),
    ]
