# Generated by Django 5.2.1 on 2025-06-26 22:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_ucsp', '0002_remove_nota_permanente_promedio_tarea_categoria_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaPrincipal',
            fields=[
                ('id_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'categoria_principal',
                'managed': True,
            },
        ),
        migrations.RemoveField(
            model_name='tarea',
            name='categoria',
        ),
        migrations.AddField(
            model_name='nota',
            name='id_tarea',
            field=models.ForeignKey(blank=True, db_column='id_tarea', help_text='Subnota vinculada (tarea, trabajo, etc.)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notas', to='my_ucsp.tarea'),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='id_curso',
            field=models.ForeignKey(db_column='id_curso', on_delete=django.db.models.deletion.CASCADE, related_name='matriculas', to='my_ucsp.curso'),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='id_usuario',
            field=models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, related_name='matriculas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='nota',
            name='id_matricula',
            field=models.ForeignKey(db_column='id_matricula', on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='my_ucsp.matricula'),
        ),
        migrations.AlterField(
            model_name='nota',
            name='nombre_nota',
            field=models.CharField(help_text='Título descriptivo de la subnota o examen', max_length=100),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ENTREGADO', 'Entregado')], default='PENDIENTE', max_length=20),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='id_curso',
            field=models.ForeignKey(db_column='id_curso', on_delete=django.db.models.deletion.CASCADE, related_name='tareas', to='my_ucsp.curso'),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='id_usuario',
            field=models.ForeignKey(blank=True, db_column='id_usuario', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tareas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='nota',
            name='id_categoria',
            field=models.ForeignKey(db_column='id_categoria', default=1, help_text='Nota principal correspondiente', on_delete=django.db.models.deletion.RESTRICT, related_name='notas', to='my_ucsp.categoriaprincipal'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tarea',
            name='id_categoria',
            field=models.ForeignKey(db_column='id_categoria', default=2, help_text='Categoría principal a la que pertenece esta tarea', on_delete=django.db.models.deletion.RESTRICT, related_name='tareas', to='my_ucsp.categoriaprincipal'),
            preserve_default=False,
        ),
    ]
