# Generated by Django 5.2.1 on 2025-06-29 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_ucsp', '0003_categoriaprincipal_remove_tarea_categoria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='tipo',
            field=models.CharField(choices=[('TAREA', 'Tarea (10%)'), ('CONTROL', 'Control (20%)')], default='TAREA', help_text='Tipo de tarea (Tarea o Control)', max_length=20),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ENTREGADO', 'Entregado'), ('RETRASADO', 'Retrasado')], default='PENDIENTE', max_length=20),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='peso_porcentaje',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Peso porcentual de la tarea en la nota final', max_digits=5),
        ),
    ]
