# Generated by Django 5.2.1 on 2025-06-29 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_ucsp', '0004_tarea_tipo_alter_tarea_estado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoriaprincipal',
            name='peso_porcentaje',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Peso porcentual de la categoría en la nota final', max_digits=5),
        ),
    ]
