# Generated by Django 5.2.1 on 2025-06-29 21:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_ucsp', '0005_categoriaprincipal_peso_porcentaje'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='tipo',
            field=models.CharField(choices=[('TAREA', 'Tarea (10%)'), ('PRACTICA_GRUPAL', 'Práctica Grupal (15%)'), ('PRACTICA_INDIVIDUAL', 'Práctica Individual (20%)'), ('CONTROL', 'Control (25%)')], default='TAREA', help_text='Tipo de tarea (Tarea o Control)', max_length=20),
        ),
        migrations.CreateModel(
            name='CursoCategoria',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('peso', models.DecimalField(decimal_places=2, max_digits=5)),
                ('id_categoria', models.ForeignKey(db_column='id_categoria', on_delete=django.db.models.deletion.CASCADE, to='my_ucsp.categoriaprincipal')),
                ('id_curso', models.ForeignKey(db_column='id_curso', on_delete=django.db.models.deletion.CASCADE, to='my_ucsp.curso')),
            ],
            options={
                'db_table': 'curso_categoria',
                'managed': True,
                'unique_together': {('id_curso', 'id_categoria')},
            },
        ),
    ]
