# Generated by Django 5.2.1 on 2025-06-29 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_ucsp', '0006_alter_tarea_tipo_cursocategoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoriaprincipal',
            name='tipo',
            field=models.CharField(choices=[('PRINCIPAL', 'Principal'), ('SECUNDARIA', 'Secundaria')], default='SECUNDARIA', help_text='Define si la categoría es una nota principal o un tipo de tarea', max_length=20),
        ),
    ]
